# -*- coding: utf-8 -*-
"""Copy of Sulphur oxide emissions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MftH8sIMy5uP7bFz2htRNbDCH2iU-QMP
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

uploaded = files.upload()

df = pd.read_csv('Luke -sulphur-oxide-emissions - .csv')

df.describe()

df.describe(exclude=np.number)

print(df)

df.drop(['Code'], axis=1)



sulphur_oxide_emissions = df

sulphur_oxide_emissions.to_csv('sulphur_oxide_emissions.csv', index=False)